// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_package_manifest.py. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "MoltenVK",
    platforms: [
        .iOS("14.0"),
        .macOS("11.0"),
        .tvOS("14.0"),
        .visionOS("1.0"),
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MoltenVK",
            url: "https://github.com/SPMForge/MoltenVK/releases/download/1.4.1-alpha.18/MoltenVK-1.4.1-alpha.18.xcframework.zip",
            checksum: "549ad6b4dfa16c7bb0c47a266fc6e184487f57ddadafa60236f61850ae542e1c"
        ),
    ]
)
