// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_package_manifest.py. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "MoltenVK",
    platforms: [
        .iOS("14.0"),
        .macOS("11.0"),
        .tvOS("14.0"),
        .visionOS("1.0"),
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MoltenVK",
            url: "https://github.com/SPMForge/MoltenVK/releases/download/1.4.1-alpha.15/MoltenVK-1.4.1-alpha.15.xcframework.zip",
            checksum: "a3e38d225787119ff20c8415989f151c3a407748e12493954f65d44d469b4748"
        ),
    ]
)
