#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

assert_file() {
    [[ -f "$ROOT_DIR/$1" ]] || { echo "missing file: $1" >&2; exit 1; }
}

assert_dir() {
    [[ -d "$ROOT_DIR/$1" ]] || { echo "missing directory: $1" >&2; exit 1; }
}

assert_executable() {
    [[ -x "$ROOT_DIR/$1" ]] || { echo "missing executable bit: $1" >&2; exit 1; }
}

assert_missing() {
    [[ ! -e "$ROOT_DIR/$1" ]] || { echo "unexpected path: $1" >&2; exit 1; }
}

assert_contains() {
    grep -Fq -- "$2" "$ROOT_DIR/$1" || { echo "missing pattern '$2' in $1" >&2; exit 1; }
}

assert_not_contains() {
    grep -Fq -- "$2" "$ROOT_DIR/$1" && { echo "unexpected pattern '$2' in $1" >&2; exit 1; } || true
}

assert_file "Package.swift"
assert_contains "Package.swift" "// swift-tools-version: 6.0"
assert_contains "Package.swift" "Generated by Scripts/SwiftPackage/render_package_manifest.py"
assert_contains "Package.swift" "name: \"MoltenVK\""
assert_contains "Package.swift" "Artifacts/MoltenVK.xcframework"
assert_contains "Package.swift" "releases/download/MoltenVK-v"
assert_contains "Package.swift" ".binaryTarget("
assert_contains "Package.swift" ".tvOS(.v14)"
assert_contains "Package.swift" ".visionOS(.v1)"
assert_not_contains "Package.swift" "MoltenVKBinary"
assert_not_contains "Package.swift" "publicHeadersPath:"
assert_not_contains "Package.swift" "path: \"Sources/MoltenVK\""
assert_not_contains "Package.swift" "linkerSettings:"
assert_not_contains "Package.swift" "SwiftPackage/PackageVersion.txt"
assert_not_contains "Package.swift" "SwiftPackage/ReleaseRepository.txt"
assert_not_contains "Package.swift" "github.com/RbBtSn0w/MoltenVK/releases"

assert_dir "Scripts/SwiftPackage"
assert_file "Scripts/SwiftPackage/common.sh"
assert_file "Scripts/SwiftPackage/build_swift_package.sh"
assert_file "Scripts/SwiftPackage/build_swift_package_dependencies.sh"
assert_file "Scripts/SwiftPackage/compute_next_alpha_version.py"
assert_file "Scripts/SwiftPackage/materialize_public_headers.py"
assert_file "Scripts/SwiftPackage/platform_config.py"
assert_file "Scripts/SwiftPackage/preflight_apple_platforms.sh"
assert_file "Scripts/SwiftPackage/publish_release.sh"
assert_file "Scripts/SwiftPackage/render_package_manifest.py"
assert_file "Scripts/SwiftPackage/report_ccache_stats.sh"
assert_file "Scripts/SwiftPackage/source_acquisition.sh"
assert_file "Scripts/SwiftPackage/validate_mergeable_xcframework.py"

assert_contains "Scripts/SwiftPackage/build_swift_package_dependencies.sh" "prepare_upstream_wrapper_workspace"
assert_contains "Scripts/SwiftPackage/build_swift_package_dependencies.sh" "sync_dependency_cache_back"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "prepare_upstream_wrapper_workspace"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "sync_workspace_outputs_back"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "archive_dynamic_framework"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MOLTENVK_MERGEABLE_VALIDATOR_PATH"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MOLTENVK_PUBLIC_HEADERS_SCRIPT"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "--xcframework-path"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "COPYFILE_DISABLE=1"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" 'HEADERS_ZIP="$ARTIFACTS_DIR/$MOLTENVK_HEADERS_ARCHIVE_NAME"'
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" 'swift package compute-checksum "$HEADERS_ZIP"'
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_API_HEADERS_DIR"
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_VULKAN_HEADERS_ROOT"
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_PUBLIC_HEADERS_SCRIPT"
assert_contains "Scripts/SwiftPackage/common.sh" "patch_tvos_mergeable_linker_mode"
assert_contains "Scripts/SwiftPackage/common.sh" 'Expected 2 tvOS dynamic classic-linker flag blocks'
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_DYNAMIC_ARTIFACT_NAME=\"MoltenVK.xcframework\""
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_STATIC_ARTIFACT_NAME=\"MoltenVK-static.xcframework\""
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_HEADERS_ARCHIVE_NAME=\"MoltenVKHeaders.zip\""
assert_contains "Scripts/SwiftPackage/common.sh" 'python3 "$MOLTENVK_PLATFORM_CONFIG_SCRIPT" render-shell'
assert_contains "Scripts/SwiftPackage/source_acquisition.sh" "refs/upstream-tags"
assert_contains "Scripts/SwiftPackage/source_acquisition.sh" "UpstreamRepository.txt"
assert_contains "Scripts/SwiftPackage/source_acquisition.sh" "UpstreamSourceRef.txt"
assert_not_contains "Scripts/SwiftPackage/source_acquisition.sh" "Sources/MoltenVK"
assert_contains "Scripts/SwiftPackage/publish_release.sh" "gh release create"
assert_contains "Scripts/SwiftPackage/publish_release.sh" "MoltenVKHeaders.zip"
assert_contains "Scripts/SwiftPackage/validate_mergeable_xcframework.py" "framework interface surface"
assert_contains "Scripts/SwiftPackage/validate_mergeable_xcframework.py" "missing framework module map"
assert_contains "Scripts/SwiftPackage/validate_mergeable_xcframework.py" "non-modular framework include"

assert_missing "Sources/MoltenVK"

assert_file "SwiftPackage/PackageVersion.txt"
assert_file "SwiftPackage/platforms.json"
assert_file "SwiftPackage/ReleaseRepository.txt"
assert_file "SwiftPackage/UpstreamRepository.txt"
assert_file "SwiftPackage/UpstreamSourceRef.txt"
assert_file "Artifacts/README.md"
assert_file "Artifacts/MoltenVK.xcframework.checksum"
assert_file "Artifacts/MoltenVK-static.xcframework.checksum"
assert_file "Artifacts/MoltenVKHeaders.checksum"
assert_contains "SwiftPackage/platforms.json" "\"id\": \"tvos\""
assert_contains "SwiftPackage/platforms.json" "\"id\": \"xros\""

assert_contains "README.md" "independent wrapper repo"
assert_contains "README.md" "refs/upstream-tags/*"
assert_contains "README.md" "-ld_classic"
assert_contains "README.md" "framework slices carry the public headers and module map internally"
assert_contains "README.md" "framework-style same-module imports"
assert_contains "Artifacts/README.md" "MoltenVKHeaders.zip"
assert_contains "Artifacts/README.md" "framework slices"
assert_contains "Artifacts/README.md" "<MoltenVK/...>"

assert_missing "SwiftPackage/package.json"
assert_missing "SwiftPackage/package-lock.json"
assert_missing "SwiftPackage/release.config.cjs"
assert_missing "Scripts/SwiftPackage/prepare_semantic_release.sh"
assert_missing ".github/workflows/CI.yml"
assert_missing "CMakeLists.txt"
assert_missing "Common"
assert_missing "Demos"
assert_missing "Docs"
assert_missing "ExternalDependencies.xcodeproj"
assert_missing "ExternalRevisions"
assert_missing "Makefile"
assert_missing "MoltenVK"
assert_missing "MoltenVKPackaging.xcodeproj"
assert_missing "MoltenVKShaderConverter"
assert_missing "Package"
assert_missing "Templates"
assert_missing "cmake"
assert_missing "fetchDependencies"
assert_missing "node_modules"
assert_missing "SwiftPackage/node_modules"
assert_missing ".github/workflows/moltenvk-spm-ci.yml"
assert_missing ".github/workflows/moltenvk-spm-release.yml"

assert_file ".github/workflows/validate-apple-release-pipeline.yml"
assert_contains ".github/workflows/validate-apple-release-pipeline.yml" "name: Validate Apple Release Pipeline"
assert_contains ".github/workflows/validate-apple-release-pipeline.yml" "Require Swift 6 toolchain"
assert_contains ".github/workflows/validate-apple-release-pipeline.yml" "Preflight Apple platforms"
assert_contains ".github/workflows/validate-apple-release-pipeline.yml" "./tests/verify_swift_package_artifacts.sh"
assert_contains ".github/workflows/validate-apple-release-pipeline.yml" "./tests/verify_swift_package_consumer.sh"
assert_contains ".github/workflows/validate-apple-release-pipeline.yml" "MoltenVKHeaders.zip"

assert_file ".github/workflows/publish-package-release-core.yml"
assert_contains ".github/workflows/publish-package-release-core.yml" "name: Publish Package Release Core"
assert_contains ".github/workflows/publish-package-release-core.yml" "selection_mode:"
assert_contains ".github/workflows/publish-package-release-core.yml" "release_channel:"
assert_contains ".github/workflows/publish-package-release-core.yml" "Require Swift 6 toolchain"
assert_contains ".github/workflows/publish-package-release-core.yml" "./Scripts/SwiftPackage/prepare_alpha_release.sh"
assert_contains ".github/workflows/publish-package-release-core.yml" "./Scripts/SwiftPackage/publish_release.sh"

assert_file ".github/workflows/publish-latest-upstream-alpha.yml"
assert_contains ".github/workflows/publish-latest-upstream-alpha.yml" "name: Publish Latest Upstream Alpha"
assert_contains ".github/workflows/publish-latest-upstream-alpha.yml" "schedule:"
assert_contains ".github/workflows/publish-latest-upstream-alpha.yml" "workflow_dispatch:"
assert_not_contains ".github/workflows/publish-latest-upstream-alpha.yml" "push:"
assert_contains ".github/workflows/publish-latest-upstream-alpha.yml" "uses: ./.github/workflows/publish-package-release-core.yml"

assert_file ".github/workflows/publish-upstream-release-manually.yml"
assert_contains ".github/workflows/publish-upstream-release-manually.yml" "name: Publish Upstream Release Manually"
assert_contains ".github/workflows/publish-upstream-release-manually.yml" "release_channel:"
assert_contains ".github/workflows/publish-upstream-release-manually.yml" "uses: ./.github/workflows/publish-package-release-core.yml"

assert_file "tests/verify_platform_config.py"
assert_file "tests/verify_public_headers.py"
assert_file "tests/verify_swift_package_artifacts.sh"
assert_file "tests/verify_swift_package_consumer.sh"
assert_file "tests/verify_validate_mergeable_xcframework.py"
assert_executable "Scripts/SwiftPackage/compute_next_alpha_version.py"
assert_executable "Scripts/SwiftPackage/materialize_public_headers.py"
assert_executable "Scripts/SwiftPackage/preflight_apple_platforms.sh"
assert_executable "Scripts/SwiftPackage/publish_release.sh"
assert_executable "Scripts/SwiftPackage/report_ccache_stats.sh"
assert_executable "Scripts/SwiftPackage/source_acquisition.sh"
assert_executable "tests/verify_platform_config.py"
assert_executable "tests/verify_public_headers.py"
assert_executable "tests/verify_swift_package_artifacts.sh"
assert_executable "tests/verify_swift_package_consumer.sh"
assert_executable "tests/verify_validate_mergeable_xcframework.py"
assert_contains "tests/verify_swift_package_consumer.sh" "MERGED_BINARY_TYPE=automatic"
assert_contains "tests/verify_swift_package_consumer.sh" "consumer_test_platform_ids"
assert_contains "tests/verify_swift_package_artifacts.sh" "ditto -x -k"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/moltenvk-manifest-renderer.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT
if python3 "$ROOT_DIR/Scripts/SwiftPackage/render_package_manifest.py" \
    --version '1.0.0"' \
    --release-repository "SPMForge/MoltenVK" \
    --checksum "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" \
    --output "$TMP_DIR/invalid.swift" >/dev/null 2>&1; then
    echo "unexpected success when rendering an invalid Package.swift manifest" >&2
    exit 1
fi

python3 "$ROOT_DIR/tests/verify_validate_mergeable_xcframework.py"
python3 "$ROOT_DIR/tests/verify_platform_config.py"

echo "MoltenVK Swift package integration layout verified"
