#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

assert_file() {
    [[ -f "$ROOT_DIR/$1" ]] || { echo "missing file: $1" >&2; exit 1; }
}

assert_dir() {
    [[ -d "$ROOT_DIR/$1" ]] || { echo "missing directory: $1" >&2; exit 1; }
}

assert_executable() {
    [[ -x "$ROOT_DIR/$1" ]] || { echo "missing executable bit: $1" >&2; exit 1; }
}

assert_missing() {
    [[ ! -e "$ROOT_DIR/$1" ]] || { echo "unexpected path: $1" >&2; exit 1; }
}

assert_contains() {
    grep -Fq -- "$2" "$ROOT_DIR/$1" || { echo "missing pattern '$2' in $1" >&2; exit 1; }
}

assert_not_contains() {
    grep -Fq -- "$2" "$ROOT_DIR/$1" && { echo "unexpected pattern '$2' in $1" >&2; exit 1; } || true
}

assert_file "Package.swift"
assert_contains "Package.swift" "// swift-tools-version: 6.0"
assert_contains "Package.swift" "Generated by Scripts/SwiftPackage/render_package_manifest.py"
assert_contains "Package.swift" "name: \"MoltenVK\""
assert_contains "Package.swift" "Artifacts/MoltenVK.xcframework"
assert_contains "Package.swift" "name: \"MoltenVKBinary\""
assert_contains "Package.swift" "publicHeadersPath: \"include\""
assert_contains "Package.swift" "releases/download/MoltenVK-v"
assert_contains "Package.swift" ".binaryTarget("
assert_not_contains "Package.swift" "SwiftPackage/PackageVersion.txt"
assert_not_contains "Package.swift" "SwiftPackage/ReleaseRepository.txt"
assert_not_contains "Package.swift" "github.com/RbBtSn0w/MoltenVK/releases"

assert_dir "Scripts/SwiftPackage"
assert_file "Scripts/SwiftPackage/common.sh"
assert_file "Scripts/SwiftPackage/build_swift_package.sh"
assert_file "Scripts/SwiftPackage/build_swift_package_dependencies.sh"
assert_file "Scripts/SwiftPackage/compute_next_alpha_version.py"
assert_file "Scripts/SwiftPackage/source_acquisition.sh"
assert_file "Scripts/SwiftPackage/publish_release.sh"
assert_file "Scripts/SwiftPackage/prepare_alpha_release.sh"
assert_file "Scripts/SwiftPackage/render_package_manifest.py"
assert_file "Scripts/SwiftPackage/validate_mergeable_xcframework.py"
assert_contains "Scripts/SwiftPackage/build_swift_package_dependencies.sh" "fetchDependencies"
assert_contains "Scripts/SwiftPackage/build_swift_package_dependencies.sh" "prepare_upstream_wrapper_workspace"
assert_contains "Scripts/SwiftPackage/build_swift_package_dependencies.sh" "sync_workspace_outputs_back"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "prepare_upstream_wrapper_workspace"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "sync_workspace_outputs_back"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "prepare_patched_swift_package_workspace"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "archive_dynamic_framework"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MOLTENVK_MERGEABLE_VALIDATOR_PATH"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "render_package_manifest.py"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MoltenVK-macOS-dynamic"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MoltenVK-iOS-dynamic"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MOLTENVK_DYNAMIC_ARTIFACT_NAME"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MOLTENVK_STATIC_ARTIFACT_NAME"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "MOLTENVK_HEADERS_ARCHIVE_NAME"
assert_contains "Scripts/SwiftPackage/build_swift_package.sh" "swift package compute-checksum"
assert_contains "Scripts/SwiftPackage/common.sh" "patch_macos_shader_converter_dependency"
assert_contains "Scripts/SwiftPackage/common.sh" "A93903C01C57E9ED00FE90DC"
assert_contains "Scripts/SwiftPackage/common.sh" "xcodebuild archive"
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_DYNAMIC_ARTIFACT_NAME=\"MoltenVK.xcframework\""
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_STATIC_ARTIFACT_NAME=\"MoltenVK-static.xcframework\""
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_MERGEABLE_VALIDATOR_PATH"
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_HEADERS_CHECKSUM_NAME"
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_PACKAGE_IOS_DEPLOYMENT_TARGET"
assert_contains "Scripts/SwiftPackage/common.sh" "MOLTENVK_PACKAGE_MACOS_DEPLOYMENT_TARGET"
assert_contains "Scripts/SwiftPackage/compute_next_alpha_version.py" "MoltenVK-v"
assert_contains "Scripts/SwiftPackage/compute_next_alpha_version.py" "--base-version"
assert_contains "Scripts/SwiftPackage/source_acquisition.sh" "refs/upstream-tags"
assert_contains "Scripts/SwiftPackage/source_acquisition.sh" "UpstreamRepository.txt"
assert_contains "Scripts/SwiftPackage/source_acquisition.sh" "UpstreamSourceRef.txt"
assert_contains "Scripts/SwiftPackage/prepare_alpha_release.sh" "./Scripts/SwiftPackage/build_swift_package.sh"
assert_contains "Scripts/SwiftPackage/prepare_alpha_release.sh" "./tests/verify_swift_package_artifacts.sh"
assert_contains "Scripts/SwiftPackage/prepare_alpha_release.sh" "./tests/verify_swift_package_consumer.sh"
assert_contains "Scripts/SwiftPackage/publish_release.sh" "gh release create"
assert_contains "Scripts/SwiftPackage/publish_release.sh" "UpstreamSourceRef.txt"

assert_dir "Sources/MoltenVK"
assert_file "Sources/MoltenVK/dummy.c"
assert_file "Sources/MoltenVK/include/module.modulemap"
assert_contains "Sources/MoltenVK/include/module.modulemap" "module MoltenVK"

assert_file "SwiftPackage/PackageVersion.txt"
assert_file "SwiftPackage/ReleaseRepository.txt"
assert_file "SwiftPackage/UpstreamRepository.txt"
assert_file "SwiftPackage/UpstreamSourceRef.txt"
assert_file "Artifacts/README.md"
assert_file "Artifacts/MoltenVK.xcframework.checksum"
assert_file "Artifacts/MoltenVK-static.xcframework.checksum"
assert_file "Artifacts/MoltenVKHeaders.checksum"

assert_contains "README.md" "independent wrapper repo"
assert_contains "README.md" "refs/upstream-tags/*"
assert_contains "README.md" "in-repo upstream source tree has been removed"
assert_missing "SwiftPackage/package.json"
assert_missing "SwiftPackage/package-lock.json"
assert_missing "SwiftPackage/release.config.cjs"
assert_missing "Scripts/SwiftPackage/prepare_semantic_release.sh"
assert_missing ".github/workflows/CI.yml"
assert_missing "CMakeLists.txt"
assert_missing "Common"
assert_missing "Demos"
assert_missing "Docs"
assert_missing "ExternalDependencies.xcodeproj"
assert_missing "ExternalRevisions"
assert_missing "Makefile"
assert_missing "MoltenVK"
assert_missing "MoltenVKPackaging.xcodeproj"
assert_missing "MoltenVKShaderConverter"
assert_missing "Package"
assert_missing "Templates"
assert_missing "cmake"
assert_missing "fetchDependencies"
assert_missing "node_modules"
assert_missing "SwiftPackage/node_modules"
assert_file "Scripts/SwiftPackage/prepare_manual_release.sh"
assert_contains "Scripts/SwiftPackage/prepare_manual_release.sh" "./Scripts/SwiftPackage/build_swift_package.sh"
assert_contains "Scripts/SwiftPackage/prepare_manual_release.sh" "./tests/verify_swift_package_artifacts.sh"
assert_contains "Scripts/SwiftPackage/prepare_manual_release.sh" "./tests/verify_swift_package_consumer.sh"
assert_file ".github/workflows/moltenvk-spm-ci.yml"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "name: MoltenVK Swift Package CI"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "runs-on: macos-15"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "Require Swift 6 toolchain"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "Prewarm MoltenVK dependencies"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "Build Swift Package artifacts"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "./tests/verify_swift_package_artifacts.sh"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "./tests/verify_swift_package_consumer.sh"
assert_contains ".github/workflows/moltenvk-spm-ci.yml" "Upload package artifacts"
assert_file ".github/workflows/moltenvk-spm-release.yml"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "branches:"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "- main"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "workflow_dispatch:"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "target_version:"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "release_intent:"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "confirm_stable:"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "runs-on: macos-15"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "fetch-depth: 0"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "Require Swift 6 toolchain"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "Prewarm MoltenVK dependencies"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "Compute next alpha version"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "Resolve upstream stable ref"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "./Scripts/SwiftPackage/compute_next_alpha_version.py"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "./Scripts/SwiftPackage/prepare_alpha_release.sh"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "./Scripts/SwiftPackage/publish_release.sh"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "./Scripts/SwiftPackage/prepare_manual_release.sh"
assert_contains ".github/workflows/moltenvk-spm-release.yml" "upstream_ref:"

assert_file "tests/verify_swift_package_artifacts.sh"
assert_file "tests/verify_swift_package_consumer.sh"
assert_executable "tests/verify_swift_package_artifacts.sh"
assert_executable "tests/verify_swift_package_consumer.sh"
assert_executable "Scripts/SwiftPackage/compute_next_alpha_version.py"
assert_executable "Scripts/SwiftPackage/prepare_manual_release.sh"
assert_executable "Scripts/SwiftPackage/prepare_alpha_release.sh"
assert_executable "Scripts/SwiftPackage/source_acquisition.sh"
assert_executable "Scripts/SwiftPackage/publish_release.sh"
assert_contains "tests/verify_swift_package_consumer.sh" "MERGED_BINARY_TYPE=automatic"
assert_contains "tests/verify_swift_package_consumer.sh" "generic/platform=iOS Simulator"
assert_contains "tests/verify_swift_package_artifacts.sh" "MOLTENVK_MERGEABLE_VALIDATOR_PATH"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/moltenvk-manifest-renderer.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT
if python3 "$ROOT_DIR/Scripts/SwiftPackage/render_package_manifest.py" \
    --version '1.0.0"' \
    --release-repository "SPMForge/MoltenVK" \
    --checksum "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" \
    --output "$TMP_DIR/invalid.swift" >/dev/null 2>&1; then
    echo "unexpected success when rendering an invalid Package.swift manifest" >&2
    exit 1
fi

echo "MoltenVK Swift package integration layout verified"
