#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import stat
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from platform_config import DEFAULT_PLATFORM_CONFIG_PATH, load_platform_config

UPSTREAM_COMMIT_RE = re.compile(r"^[0-9a-f]{40}$")

UPSTREAM_PBXPROJ_PATCHES = (
    {
        "relative_path": "ExternalDependencies.xcodeproj/project.pbxproj",
        "expected_tvos_replacements": 2,
        "expected_xros_blocks": 4,
    },
    {
        "relative_path": "MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj",
        "expected_tvos_replacements": 2,
        "expected_xros_blocks": 2,
    },
    {
        "relative_path": "MoltenVK/MoltenVK.xcodeproj/project.pbxproj",
        "expected_tvos_replacements": 2,
        "expected_xros_blocks": 4,
    },
)

REVISION_SCRIPT_TEMPLATE = """#!/bin/bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
upstream_commit_file="${MVK_UPSTREAM_COMMIT_FILE:-$script_dir/../SwiftPackage/UpstreamCommit.txt}"

if MVK_GIT_REV="$(git -C "$script_dir/.." rev-parse HEAD 2>/dev/null)"; then
    :
elif [[ -n "${MVK_UPSTREAM_COMMIT:-}" ]]; then
    MVK_GIT_REV="${MVK_UPSTREAM_COMMIT}"
elif [[ -f "$upstream_commit_file" ]]; then
    MVK_GIT_REV="$(tr -d '[:space:]' < "$upstream_commit_file")"
    [[ -n "$MVK_GIT_REV" ]] || {
        echo "error: upstream commit file is empty: $upstream_commit_file" >&2
        exit 1
    }
else
    echo "error: unable to determine MoltenVK revision; neither git metadata nor $upstream_commit_file is available" >&2
    exit 1
fi

MVK_HDR_FILE="${BUILT_PRODUCTS_DIR}/mvkGitRevDerived.h"
echo "// Auto-generated by MoltenVK" > "${MVK_HDR_FILE}"
echo "static const char* mvkRevString = \\"${MVK_GIT_REV}\\";" >> "${MVK_HDR_FILE}"
"""


def ensure_workspace_root(path: Path) -> Path:
    workspace_root = path.resolve()
    if not workspace_root.is_dir():
        raise ValueError(f"workspace root does not exist: {workspace_root}")
    return workspace_root


def write_upstream_commit_file(workspace_root: Path, upstream_commit: str) -> Path:
    if not UPSTREAM_COMMIT_RE.fullmatch(upstream_commit):
        raise ValueError("upstream commit must be a 40-character lowercase hexadecimal SHA")
    commit_path = workspace_root / "SwiftPackage" / "UpstreamCommit.txt"
    commit_path.parent.mkdir(parents=True, exist_ok=True)
    commit_path.write_text(f"{upstream_commit}\n", encoding="utf-8")
    return commit_path


def patch_revision_script(script_path: Path) -> None:
    if not script_path.is_file():
        raise ValueError(f"missing revision script: {script_path}")
    script_path.write_text(REVISION_SCRIPT_TEMPLATE, encoding="utf-8")
    script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def patch_pbxproj_deployment_targets(
    pbxproj_path: Path,
    *,
    tvos_deployment_target: str,
    xros_deployment_target: str,
    expected_tvos_replacements: int,
    expected_xros_blocks: int,
) -> None:
    if not pbxproj_path.is_file():
        raise ValueError(f"missing project file: {pbxproj_path}")

    text = pbxproj_path.read_text(encoding="utf-8")

    tvos_pattern = re.compile(r"(?P<indent>\s*)TVOS_DEPLOYMENT_TARGET = [0-9.]+;")
    text, tvos_replacements = tvos_pattern.subn(
        lambda match: f"{match.group('indent')}TVOS_DEPLOYMENT_TARGET = {tvos_deployment_target};",
        text,
    )
    if tvos_replacements != expected_tvos_replacements:
        raise ValueError(
            f"Expected {expected_tvos_replacements} TVOS_DEPLOYMENT_TARGET replacements in {pbxproj_path}, found {tvos_replacements}"
        )

    xros_pattern = re.compile(
        r"(?P<indent>\s*)SDKROOT = xros;\n(?:(?P=indent)XROS_DEPLOYMENT_TARGET = [0-9.]+;\n)?"
    )
    text, xros_blocks = xros_pattern.subn(
        lambda match: (
            f"{match.group('indent')}SDKROOT = xros;\n"
            f"{match.group('indent')}XROS_DEPLOYMENT_TARGET = {xros_deployment_target};\n"
        ),
        text,
    )
    if xros_blocks != expected_xros_blocks:
        raise ValueError(f"Expected {expected_xros_blocks} xros SDKROOT blocks in {pbxproj_path}, found {xros_blocks}")

    pbxproj_path.write_text(text, encoding="utf-8")


def patch_workspace(workspace_root: Path, upstream_commit: str, platform_config: dict) -> None:
    workspace_root = ensure_workspace_root(workspace_root)
    write_upstream_commit_file(workspace_root, upstream_commit)
    patch_revision_script(workspace_root / "Scripts" / "gen_moltenvk_rev_hdr.sh")

    tvos_target = platform_config["deployment_targets"]["tvos"]["version"]
    xros_target = platform_config["deployment_targets"]["visionos"]["version"]
    for patch in UPSTREAM_PBXPROJ_PATCHES:
        patch_pbxproj_deployment_targets(
            workspace_root / str(patch["relative_path"]),
            tvos_deployment_target=tvos_target,
            xros_deployment_target=xros_target,
            expected_tvos_replacements=int(patch["expected_tvos_replacements"]),
            expected_xros_blocks=int(patch["expected_xros_blocks"]),
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Patch a prepared upstream MoltenVK workspace for wrapper packaging.")
    parser.add_argument("--workspace-root", required=True, help="Prepared upstream workspace root.")
    parser.add_argument("--upstream-commit", required=True, help="Resolved upstream commit SHA.")
    parser.add_argument(
        "--platform-config",
        default=str(DEFAULT_PLATFORM_CONFIG_PATH),
        help="Path to the centralized platform config JSON file.",
    )
    args = parser.parse_args()

    patch_workspace(
        Path(args.workspace_root),
        args.upstream_commit,
        load_platform_config(args.platform_config),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
