#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from platform_config import DEFAULT_PLATFORM_CONFIG_PATH, load_platform_config, manifest_platform_entries

CHECKSUM_RE = re.compile(r"^[0-9a-f]{64}$")
RELEASE_REPOSITORY_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$")
DEPLOYMENT_TARGET_RE = re.compile(r"^[0-9]+$")


def validate_release_repository(value: str) -> str:
    repository = value.strip()
    if not RELEASE_REPOSITORY_RE.fullmatch(repository):
        raise ValueError(
            "release repository must be a GitHub owner/repo identifier containing only letters, digits, '.', '_' or '-'."
        )
    return repository


def validate_version(value: str) -> str:
    version = value.strip()
    if not SEMVER_RE.fullmatch(version):
        raise ValueError("version must be a SemVer string like 1.2.3, 1.2.3-beta.1, or 1.2.3+build.5.")
    return version


def validate_checksum(value: str) -> str:
    checksum = value.strip().lower()
    if not CHECKSUM_RE.fullmatch(checksum):
        raise ValueError("checksum must be a 64-character lowercase hexadecimal digest.")
    return checksum


def validate_deployment_target(value: str, platform_name: str) -> str:
    target = value.strip()
    if not DEPLOYMENT_TARGET_RE.fullmatch(target):
        raise ValueError(f"{platform_name} deployment target must be a whole major version such as 11 or 14.")
    return target


def render_manifest(
    version: str,
    release_repository: str,
    checksum: str,
    platform_entries: list[tuple[str, str]],
) -> str:
    remote_url = (
        f"https://github.com/{release_repository}/releases/download/"
        f"{version}/MoltenVK.xcframework.zip"
    )

    rendered_platforms = "\n".join(
        f"        .{swiftpm_platform}(.v{deployment_target}),"
        for swiftpm_platform, deployment_target in platform_entries
    )

    return f"""// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_package_manifest.py. Do not edit by hand.

import Foundation
import PackageDescription

let localArtifactPath = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .appendingPathComponent("Artifacts/MoltenVK.xcframework")
    .path

let remoteArtifactURL = "{remote_url}"
let remoteChecksum = "{checksum}"

let moltenVKTarget: Target = {{
    if FileManager.default.fileExists(atPath: localArtifactPath) {{
        return .binaryTarget(
            name: "MoltenVK",
            path: "Artifacts/MoltenVK.xcframework"
        )
    }}

    return .binaryTarget(
        name: "MoltenVK",
        url: remoteArtifactURL,
        checksum: remoteChecksum
    )
}}()

let package = Package(
    name: "MoltenVK",
    platforms: [
{rendered_platforms}
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        moltenVKTarget,
    ]
)
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the MoltenVK Package.swift manifest from release metadata.")
    parser.add_argument("--version", required=True, help="Package version and release tag, expressed as plain SemVer.")
    parser.add_argument("--release-repository", required=True, help="GitHub owner/repository that hosts release assets.")
    parser.add_argument("--checksum", required=True, help="SwiftPM checksum for the MoltenVK.xcframework zip.")
    parser.add_argument(
        "--platform-config",
        default=str(DEFAULT_PLATFORM_CONFIG_PATH),
        help="Path to the centralized platform config JSON file.",
    )
    parser.add_argument("--ios-deployment-target", help="Legacy override for the SwiftPM iOS deployment target major version.")
    parser.add_argument("--macos-deployment-target", help="Legacy override for the SwiftPM macOS deployment target major version.")
    parser.add_argument("--output", default="Package.swift", help="Manifest output path.")
    args = parser.parse_args()

    try:
        platform_entries = [
            (
                swiftpm_platform,
                validate_deployment_target(deployment_target, swiftpm_platform),
            )
            for swiftpm_platform, deployment_target in manifest_platform_entries(load_platform_config(args.platform_config))
        ]
        platform_overrides = {
            "iOS": args.ios_deployment_target,
            "macOS": args.macos_deployment_target,
        }
        platform_entries = [
            (
                swiftpm_platform,
                validate_deployment_target(platform_overrides[swiftpm_platform], swiftpm_platform)
                if platform_overrides.get(swiftpm_platform)
                else deployment_target,
            )
            for swiftpm_platform, deployment_target in platform_entries
        ]
        manifest = render_manifest(
            validate_version(args.version),
            validate_release_repository(args.release_repository),
            validate_checksum(args.checksum),
            platform_entries,
        )
    except ValueError as error:
        parser.error(str(error))
    output_path = Path(args.output)
    output_path.write_text(manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
