#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from pathlib import Path

CHECKSUM_RE = re.compile(r"^[0-9a-f]{64}$")
RELEASE_REPOSITORY_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$")


def validate_release_repository(value: str) -> str:
    repository = value.strip()
    if not RELEASE_REPOSITORY_RE.fullmatch(repository):
        raise ValueError(
            "release repository must be a GitHub owner/repo identifier containing only letters, digits, '.', '_' or '-'."
        )
    return repository


def validate_version(value: str) -> str:
    version = value.strip()
    if not SEMVER_RE.fullmatch(version):
        raise ValueError("version must be a SemVer string like 1.2.3, 1.2.3-beta.1, or 1.2.3+build.5.")
    return version


def validate_checksum(value: str) -> str:
    checksum = value.strip().lower()
    if not CHECKSUM_RE.fullmatch(checksum):
        raise ValueError("checksum must be a 64-character lowercase hexadecimal digest.")
    return checksum


def render_manifest(version: str, release_repository: str, checksum: str) -> str:
    remote_url = (
        f"https://github.com/{release_repository}/releases/download/"
        f"MoltenVK-v{version}/MoltenVK.xcframework.zip"
    )

    return f"""// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_package_manifest.py. Do not edit by hand.

import Foundation
import PackageDescription

let localArtifactPath = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .appendingPathComponent("Artifacts/MoltenVK.xcframework")
    .path

let remoteArtifactURL = "{remote_url}"
let remoteChecksum = "{checksum}"

let moltenVKTarget: Target = {{
    if FileManager.default.fileExists(atPath: localArtifactPath) {{
        return .binaryTarget(
            name: "MoltenVKBinary",
            path: "Artifacts/MoltenVK.xcframework"
        )
    }}

    return .binaryTarget(
        name: "MoltenVKBinary",
        url: remoteArtifactURL,
        checksum: remoteChecksum
    )
}}()

let package = Package(
    name: "MoltenVK",
    platforms: [
        .iOS(.v14),
        .macOS(.v11),
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        .target(
            name: "MoltenVK",
            dependencies: ["MoltenVKBinary"],
            path: "Sources/MoltenVK",
            publicHeadersPath: "include",
            linkerSettings: [
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Foundation"),
                .linkedFramework("Metal"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("UIKit", .when(platforms: [.iOS])),
                .linkedFramework("Cocoa", .when(platforms: [.macOS])),
                .linkedFramework("IOKit", .when(platforms: [.macOS])),
                .linkedFramework("IOSurface", .when(platforms: [.macOS])),
                .linkedLibrary("c++"),
            ]
        ),
        moltenVKTarget,
    ]
)
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the MoltenVK Package.swift manifest from release metadata.")
    parser.add_argument("--version", required=True, help="Package version used in the release tag.")
    parser.add_argument("--release-repository", required=True, help="GitHub owner/repository that hosts release assets.")
    parser.add_argument("--checksum", required=True, help="SwiftPM checksum for the MoltenVK.xcframework zip.")
    parser.add_argument("--output", default="Package.swift", help="Manifest output path.")
    args = parser.parse_args()

    try:
        manifest = render_manifest(
            validate_version(args.version),
            validate_release_repository(args.release_repository),
            validate_checksum(args.checksum),
        )
    except ValueError as error:
        parser.error(str(error))
    output_path = Path(args.output)
    output_path.write_text(manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
