#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path
import sys

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from platform_config import DEFAULT_PLATFORM_CONFIG_PATH, load_platform_config, manifest_platform_entries


def render_manifest(artifact_relative_path: str, platform_entries: list[tuple[str, str]]) -> str:
    rendered_platforms = "\n".join(
        f'        .{swiftpm_platform}("{deployment_target}"),'
        for swiftpm_platform, deployment_target in platform_entries
    )

    return f"""// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_local_dev_package_manifest.py. Local-only helper.

import PackageDescription

let package = Package(
    name: "MoltenVK",
    platforms: [
{rendered_platforms}
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MoltenVK",
            path: "{artifact_relative_path}"
        ),
    ]
)
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Render a local-only MoltenVK Package.swift manifest that points at a checked-out XCFramework.")
    parser.add_argument("--artifact-relative-path", default="Artifacts/MoltenVK.xcframework")
    parser.add_argument("--platform-config", default=str(DEFAULT_PLATFORM_CONFIG_PATH))
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    platform_entries = manifest_platform_entries(load_platform_config(args.platform_config))
    Path(args.output).write_text(render_manifest(args.artifact_relative_path, platform_entries))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
